name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install dependencies and build
      working-directory: delivery-app
      run: |
        rm -rf node_modules
        rm -rf package-lock.json
        rm yarn.lock
        yarn cache clean
        yarn install
        yarn global add react-scripts
        yarn build

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Test
      working-directory: delivery-app
      run: yarn run test

